### PR TITLE
Add ipython and ctrl+c

### PR DESCRIPTION
**Pull request by abenassi**
Hey! In this pull request I'm doing the following changes: 
- Add ipython support for rlundo (undoableipython.py)
- Change rlundo so now it calls undoablepython or undoableipython automatically when recognizes the interpreter, together with rewrite.py
- Ipython and python undo will work also with KeyboardInterrupt (ctrl+c)
- Update the readme reflecting these changes and add a gif example to show ctrl+c possibility.

Let me know any thing I should change or if you don't like the readme changes!

### CODE REVIEW

**Comment by thomasballinger** [comment]
Undo in IPython, whoo!

Feature-wise, I think this is great for now, though eventually it's be nice to use a key besides ctrl-c, and to do that we probably need to intercept Python/IPython's readline. We're using GitHub issues now, so I'll create one for this after we get this merged.

Implementation-wise, this is a pretty big monkey-patch for IPython. Could we just patch self.raw_input_original instead? I know this is a prototype, but that's a lot of lines that could potentially change in IPython. (Also, just something to keep in mind: we'll want to detect the version of IPython and have other fixes available for other versions once this starts breaking. This is fine for now, let's wait until that's a problem.)

I'd rather not shell out with os.system, which will result in 3 Python instances running instead of the two we need - can we import and run the rewrite functionality we need instead?

The gif looks great, but I'd rather not have it in the repo - eventually we might have a lot of these and lugging them around every code checkout could get old. I'm happy to host it at ballingt.com, or you're welcome to put it somewhere.

**Comment by abenassi** [comment]
Alright! I'll try to use only self.raw_input_original, though last time I couldn't manage to do it just inside that method.

Also I'll change the way to use rewrite so we don't shell it out. 

Oh sure, if you can host it there we can just change the link. Since I don't have any other server I usually use the repo for this.

I see the build has failed! And it's because 3 tests are not being ran as they don't recognize a few modules that are there... I remember we've seen this before but we couldn't notice why this is happening.

**Comment by thomasballinger** [comment]
@abenassi I don't know what the problem would have been for certain, but perhaps the `self.raw_input_original` attribute is shadowing the patched method on the class - if that's the case, you might add a property on the class:

``` .py
>>> class Node(object):
...     pass
...
>>> n = Node()
>>> n.a = 1
>>> Node.a = property(lambda self: 2)
>>> n.a
2
>>>
```

**Comment by abenassi** [comment]
https://www.dropbox.com/s/0vlwkg4zve5gkjv/Screenshot%202015-04-27%2015.48.00.png?dl=0

I can't set raw_original_input property, weird stuff happen.

**Comment by abenassi** [comment]
Finally I have replaced TerminalInteractiveShell.raw_input() instead of TerminalInteractiveShell.raw_input_original(). It would be still better to replace the other one, but at least this one is less code to maintain than TerminalInteractiveShell.interact(). Keeping old one in the module anyway, for future reference.

**Comment by abenassi** [comment]
Alright, now is raw_input_original() !

**Comment by thomasballinger** [comment]
Merged, thanks so much!

**Comment by abenassi** [comment]
Awesome, I'm glad!

**Pull request closed without merging**
